export const ROW_12 = [
  [
    { reserved: false, seat: "1", row: "1" },
    { reserved: false, seat: "2", row: "1" },
    { reserved: false, seat: "3", row: "1" },
    { reserved: false, seat: "4", row: "1" },
    { reserved: true, seat: "5", row: "1" },
    { reserved: false, seat: "6", row: "1" },
  ],
  [
    { reserved: false, seat: "7", row: "2" },
    { reserved: false, seat: "8", row: "2" },
    { reserved: false, seat: "9", row: "2" },
    { reserved: false, seat: "10", row: "2" },
    { reserved: false, seat: "11", row: "2" },
    { reserved: false, seat: "12", row: "2" },
    { reserved: false, seat: "13", row: "2" },
    { reserved: false, seat: "14", row: "2" },
  ],
];

export const ROW_3 = [
  { reserved: true, seat: "15", row: "3" },
  { reserved: true, seat: "16", row: "3" },
  { reserved: true, seat: "17", row: "3" },
  { reserved: true, seat: "18", row: "3" },
  { reserved: true, seat: "19", row: "3" },
  { reserved: true, seat: "20", row: "3" },
  { reserved: true, seat: "21", row: "3" },
  { reserved: true, seat: "22", row: "3" },
];

export const ROWS = [
  { reserved: false, seat: "23", row: "4" },
  { reserved: true, seat: "24", row: "4" },
  { reserved: true, seat: "25", row: "4" },
  { reserved: false, seat: "26", row: "4" },
  { reserved: true, seat: "27", row: "4" },
  { reserved: false, seat: "28", row: "4" },
  { reserved: true, seat: "29", row: "4" },
  { reserved: false, seat: "30", row: "4" },
  { reserved: false, seat: "31", row: "4" },
  { reserved: true, seat: "32", row: "4" },
  { reserved: false, seat: "33", row: "5" },
  { reserved: false, seat: "34", row: "5" },
  { reserved: false, seat: "35", row: "5" },
  { reserved: false, seat: "36", row: "5" },
  { reserved: false, seat: "37", row: "5" },
  { reserved: false, seat: "38", row: "5" },
  { reserved: false, seat: "39", row: "5" },
  { reserved: false, seat: "40", row: "5" },
  { reserved: false, seat: "41", row: "5" },
  { reserved: false, seat: "42", row: "5" },
  { reserved: true, seat: "43", row: "6" },
  { reserved: false, seat: "44", row: "6" },
  { reserved: false, seat: "45", row: "6" },
  { reserved: true, seat: "46", row: "6" },
  { reserved: true, seat: "47", row: "6" },
  { reserved: false, seat: "48", row: "6" },
  { reserved: true, seat: "49", row: "6" },
  { reserved: false, seat: "50", row: "6" },
  { reserved: false, seat: "51", row: "6" },
  { reserved: false, seat: "52", row: "6" },
];
